<?php
if( function_exists('acf_add_local_field_group') ):

    // GROUP : Activation des customs post
    acf_add_local_field_group(array(
        'key' => 'group_5d7126e8db53f',
        'title' => 'Activation des customs post',
        'fields' => array(
            array(
                'key' => 'field_5d712714ae53c',
                'label' => 'Équipe de recherche',
                'name' => 'sedoo-research-team',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
            array(
                'key' => 'field_5d712871f36d4',
                'label' => 'Plateformes',
                'name' => 'sedoo-platform',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
            array(
                'key' => 'field_5de50ff1f0c3e',
                'label' => 'Axes transverses',
                'name' => 'sedoo-axe',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
            array(
                'key' => 'field_5e39896f585b3',
                'label' => 'Projets',
                'name' => 'sedoo-project',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
            array(
                'key' => 'field_5e39898c967df',
                'label' => 'Services d\'observation',
                'name' => 'sedoo-sno',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-custom-posts-type',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    // GROUP : Activation des customs taxonomies
    acf_add_local_field_group(array(
        'key' => 'group_5d712dfbac85e',
        'title' => 'Activation des customs taxonomies',
        'fields' => array(
            array(
                'key' => 'field_5d7130aa77bb7',
                'label' => 'Thématiques',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5d7130aa77bb8',
                'label' => 'Thématiques',
                'name' => 'sedoo-theme-labo',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
            array(
                'key' => 'field_5d7130aa77bb9',
                'label' => 'Association avec le Custom Post',
                'name' => 'type_of_content',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5d7130aa77bb8',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'location' => 'Emplacements',
                    'event' => 'Évènements',
                    'feedzy_categories' => 'Feed Categories',
                    'sedoo-platform' => 'Plateformes',
                    'sedoo-research-team' => 'Équipes de recherche',
                    'aeris-team' => 'Equipes',
                    'aeris-member' => 'Membres',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 1,
                'ui' => 1,
                'ajax' => 1,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5d712e8b65aca',
                'label' => 'Plateformes',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5d712ead65acb',
                'label' => 'Tag plateformes',
                'name' => 'sedoo-platform-tag',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
            array(
                'key' => 'field_5d712ed965acc',
                'label' => 'Association avec le Custom Post',
                'name' => 'type_of_content',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5d712ead65acb',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'location' => 'Emplacements',
                    'event' => 'Évènements',
                    'feedzy_categories' => 'Feed Categories',
                    'sedoo-platform' => 'Plateformes',
                    'sedoo-research-team' => 'Équipes de recherche',
                    'aeris-team' => 'Equipes',
                    'aeris-member' => 'Membres',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 1,
                'ui' => 1,
                'ajax' => 1,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5d713145b4e7a',
                'label' => 'Equipes',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5d713145b4e7b',
                'label' => 'Tag équipe de recherche',
                'name' => 'sedoo-research-team-tag',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
            array(
                'key' => 'field_5d713145b4e7c',
                'label' => 'Association avec le Custom Post',
                'name' => 'type_of_content',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5d713145b4e7b',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'location' => 'Emplacements',
                    'event' => 'Évènements',
                    'feedzy_categories' => 'Feed Categories',
                    'sedoo-platform' => 'Plateformes',
                    'sedoo-research-team' => 'Équipes de recherche',
                    'aeris-team' => 'Equipes',
                    'aeris-member' => 'Membres',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 1,
                'ui' => 1,
                'ajax' => 1,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5de51181a47b2',
                'label' => 'Axes transverses',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5de511a3a47b3',
                'label' => 'Tag axe transverse',
                'name' => 'sedoo-axe-tag',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
            array(
                'key' => 'field_5de511c1a47b4',
                'label' => 'Association avec le Custom Post',
                'name' => 'type_of_content',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5d713145b4e7b',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'location' => 'Emplacements',
                    'event' => 'Évènements',
                    'feedzy_categories' => 'Feed Categories',
                    'sedoo-platform' => 'Plateformes',
                    'sedoo-research-team' => 'Équipes de recherche',
                    'aeris-team' => 'Equipes',
                    'aeris-member' => 'Membres',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 1,
                'ui' => 1,
                'ajax' => 1,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5e398c7ce7517',
                'label' => 'Projects',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5e398c95e7518',
                'label' => 'Tag project',
                'name' => 'sedoo-project-tag',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Activé',
                'ui_off_text' => 'Désactivé',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-custom-taxonomies',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // GROUP : Custom block Related Content
    acf_add_local_field_group(array(
        'key' => 'group_5d80ab6e372f7',
        'title' => 'Custom block Related Content',
        'fields' => array(
            array(
                'key' => 'field_5d80ab6e4602c',
                'label' => 'Titre de la zone',
                'name' => 'relatedContentTitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d80ab6e46017',
                'label' => 'Type de contenu',
                'name' => 'relatedContentTypeOfContent',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'location' => 'Emplacements',
                    'event' => 'Évènements',
                    'feedzy_categories' => 'Feed Categories',
                    'sedoo-platform' => 'Plateformes',
                    'sedoo-research-team' => 'Équipes de recherche',
                    'aeris-team' => 'Equipes',
                    'aeris-member' => 'Membres',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5d80ab6e46031',
                'label' => 'Taxonomie',
                'name' => 'relatedContentTaxonomies',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'event-tags' => 'Étiquettes d’évènement',
                    'event-categories' => 'Catégories',
                    'sedoo-theme-labo' => 'Thématiques',
                    'sedoo-platform-tag' => 'Platform Tags',
                    'sedoo-research-team-tag' => 'Research Team Tags',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5d80ab6e46036',
                'label' => 'Nombre de posts',
                'name' => 'post_number',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => 12,
                'step' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_5d80ab6e4603c',
                'label' => 'Offset',
                'name' => 'post_offset',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/sedoo-labtools-relatedblock',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;
?>