<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5d6d146e22177',
        'title' => 'Custom blocks zone',
        'fields' => array(
            array(
                'key' => 'field_5d6d14933870f',
                'label' => 'Colonne de droite',
                'name' => 'right_column',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_5d6d1647ce307' => array(
                        'key' => 'layout_5d6d1647ce307',
                        'name' => 'related_content',
                        'label' => 'Contenu transverse',
                        'display' => 'table',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d6d186238710',
                                'label' => 'Titre',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5d6d18cb38711',
                                'label' => 'Type de contenu',
                                'name' => 'type_of_content',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'location' => 'Emplacements',
                                    'event' => 'Évènements',
                                    'feedzy_categories' => 'Feed Categories',
                                    'sedoo-platform' => 'Plateformes',
                                    'sedoo-research-team' => 'Équipes de recherche',
                                    'aeris-team' => 'Equipes',
                                    'aeris-member' => 'Membres',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_5d6d24617ed70',
                                'label' => 'Taxonomie',
                                'name' => 'taxonomies',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'event-tags' => 'Étiquettes d’évènement',
                                    'event-categories' => 'Catégories',
                                    'sedoo-theme-labo' => 'Thématiques',
                                    'sedoo-platform-tag' => 'Platform Tags',
                                    'sedoo-research-team-tag' => 'Research Team Tags',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_5d6d2cc989b78',
                                'label' => 'Nombre de posts',
                                'name' => 'post_number',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => -1,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_5d6d2d0089b79',
                                'label' => 'Offset',
                                'name' => 'post_offset',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_5d6d32dbbc994' => array(
                        'key' => 'layout_5d6d32dbbc994',
                        'name' => 'related_news',
                        'label' => 'Actualités en relation',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d6d330cbc995',
                                'label' => 'Titre de la zone',
                                'name' => 'title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5d6d3327bc996',
                                'label' => 'Taxonomie',
                                'name' => 'taxonomies',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'event-tags' => 'Étiquettes d’évènement',
                                    'event-categories' => 'Catégories',
                                    'sedoo-theme-labo' => 'Thématiques',
                                    'sedoo-platform-tag' => 'Platform Tags',
                                    'sedoo-research-team-tag' => 'Research Team Tags',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_5d6d3345bc997',
                                'label' => 'Nombre de posts',
                                'name' => 'post_number',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => -1,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array(
                                'key' => 'field_5d6d334dbc998',
                                'label' => 'Offset',
                                'name' => 'post_offset_copie',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'button_label' => 'Ajouter un élément',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sedoo-research-team',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;
?>